apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vzaicevs-me-tls
spec:
  secretName: vzaicevs-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vzaicevs.me
  dnsNames:
    - vzaicevs.me
    - www.vzaicevs.me
